apiVersion: v1
kind: Service
metadata:
  name: shopping-backend
  labels:
    app: shopping-backend
spec:
  type: ClusterIP
  selector:
    app: shopping-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
